site_name: Multi Rotor Club, SUTD
site_url: http://multirotorsociety.github.io
site_description: >-
    Multi Rotor Club, SUTD is 5th Row Club at SUTD (Singapore University of Technology and Design).
    We are a club that deals in many types remote controlled (RC) vehicles such as drones, cars and boats, although 
    our main focus is on building and flying MultiRotors of varying levels of autonomy.
site_author: Sean Yeo, Kian Wee
copyright: MIT License

repo_url: https://github.com/multirotorsociety/multirotorsociety.github.io
repo_name: multirotorsociety.github.io
edit_uri: ''

nav:
    - Home: 'index.md'
    - About this Page: 
        - 'about.md'

theme:
    name: material
    custom_dir: overrides
    palette: 
        primary: light blue
        accent: indigo
    font:
        text: Noto Sans
    features:
        - navigation.tabs
    icon:
        logo: material/quadcopter

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/multirotorsociety
        - icon: fontawesome/brands/instagram
          link: https://instagram.com/sutdrones

plugins:
    - search


markdown_extensions:
    - meta
    - toc
    - tables
    - fenced_code
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - attr_list